Updated logMoji to use protocols instead of a normal dictonary
adilanchian/LogMoji pull request #1
Opened 2020-03-26 16:34 UTC by mustiikhalil

The current Implementation uses a protocol instead of normal dictionary. which allows the code to be contained within the protocol itself only. 

```swift
enum Errors: String, State {
    case critical, success, warning

     var emoji: String {...} \\ some switch statement here
     var name: String { self.rawValue }
}
```
then users can either use it like this:
```swift
LogMoji.logger.logWith(state: Errors.success, message: "I am a successful LogMoji message!")
```
or 
```swift
func log(state: Errors, message: String) {
    LogMoji.logger.logWith(state: state, message: message)
}
```

2020-03-27 04:30 UTC, adilanchian requested changes
Looks SICK. Just left a few comments her :)

2020-03-27 04:30 UTC, adilanchian commented on Example/LogMoji/ViewController.swift
> +enum Errors: String, State {
I feel like this is counterproductive to call this `Errors` as these are not all errors! Can we call this something along the lines of `States` or `LogStates`? Whatever you think is better here!

2020-03-27 04:30 UTC, adilanchian commented on LogMoji/Classes/State.swift
> +    /// Emoji that would be used by the library to print the color of the state
I don't understand this comment really. What does the emoji have to do with the color of the state?

2020-03-27 04:30 UTC, adilanchian commented on README.md
> +enum Errors: String, State {
Same here for the errors name

2020-03-28 16:18 UTC, mustiikhalil commented
Fixed

2020-03-30 04:59 UTC, adilanchian approved these changes
LIT.

2020-03-30 04:59 UTC, merged